"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$fill$battery$time$line_break$character'
continuation_prompt = '[ó±ª ](bright-black)'

[character]
success_symbol = ' [î®¦ ](bold bright-green)'
error_symbol = ' [î¯ ](bold bright-red)'

[status]
style = 'bold bright-red'
symbol = 'îª‡ '

[git_branch]
style = 'bold blue'
symbol = '[îœ¥](bold bright-blue) '

[git_commit]
disabled = false

[git_metrics]
disabled = false
format = "([ï©](bright-red)[{](red) [+$added]($added_style)[/](bold bright-black)[-$deleted]($deleted_style) [}](red) )"

[git_status]
format = "([îœ¨\\[ $all_status$ahead_behind \\]]($style) )"
modified = "[ï© ](bright-red)"
conflicted = "[ó°•š ](bright-red)"
staged = "[ï§ ](green)"
ahead = "[ó°§‡ ](bright-yellow)"
behind = "[ó°¦¿ ](bright-magenta)"
diverged = "[ó°§ˆ ](bright-red)"
stashed = "[ï…•](bright-yellow)"
untracked = "[ï„¨](bright-cyan)"
style = 'bold bright-blue'

[time]
disabled = false
use_12hr = true
format = '[î™ $time]($style) '
style = 'bold italic bright-black'

[memory_usage]
disabled = false
threshold = 80

# [os]
# disabled = false

# [username]
# show_always = true

[sudo]
disabled = false
symbol = '[ï‚œ ](bold bright-blue) '

[battery]
disabled = false
full_symbol = 'ó°¹'
charging_symbol = 'ó°‚„'
discharging_symbol = 'ó°‚Œ'
[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'
charging_symbol = 'ó°¢œ '
discharging_symbol = 'ó°º '
[[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 20
style = 'bold yellow'
charging_symbol = 'ó°‚† '
discharging_symbol = 'ó°» '
[[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 30
style = 'bold yellow'
charging_symbol = 'ó°‚‡ '
discharging_symbol = 'ó°¼ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 40
style = 'bold green'
charging_symbol = 'ó°‚ˆ '
discharging_symbol = 'ó°½ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 50
style = 'bold green'
charging_symbol = 'ó°¢ '
discharging_symbol = 'ó°¾ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 60
style = 'bold green'
charging_symbol = 'ó°‚‰ '
discharging_symbol = 'ó°¿ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 70
style = 'bold green'
charging_symbol = 'ó°¢ '
discharging_symbol = 'ó°‚€ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 80
style = 'bold green'
charging_symbol = 'ó°‚Š '
discharging_symbol = 'ó°‚ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 90
style = 'bold green'
charging_symbol = 'ó°‚‹ '
discharging_symbol = 'ó°‚‚ '
[[battery.display]] # when capacity is between 30% and 100%
threshold = 100
style = 'bold green'
charging_symbol = 'ó°‚… '
discharging_symbol = 'ó±Ÿ '
