"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = true

# format = """$all$darcharacter"""
# right_format = """$all"""

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red) '

[git_branch]
style = 'bold blue'
symbol = "[\ue725](bold bright-blue) "

[git_metrics]
disabled = false
format = "([\uf069{](bold red)[+$added]($added_style)[/](bold dark-white)[-$deleted]($deleted_style)[}](bold red) )"

[git_status]
format = "([\ue728\\[$all_status$ahead_behind\\]]($style) )"
modified = "[\uf069](bold red)"
staged = "[\uf067](bold green)"
ahead = "[\uf062](bold bright-yellow)"
behind = "[\uf063](bold bright-magenta)"
# diverged = "[\f09c8 \Udb82ddc8](bold bright-red)"
style = 'bold bright-purple'

# [battery]
# full_symbol = 'ğŸ”‹ '
# charging_symbol = 'âš¡ï¸ '
# discharging_symbol = 'ğŸ’€ '
# [[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
# threshold = 30
# style = 'bold yellow'
